# Generated by Django 3.2.16 on 2023-05-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_question', models.IntegerField(db_index=True, unique=True)),
                ('question', models.TextField(blank=True, max_length=255, unique=True)),
                ('answer', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(blank=True)),
            ],
        ),
    ]
